cmd_/home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.o :=  gcc-4.6 -Wp,-MD,/home/primary/Downloads/intel-536-537/coredrv/.wwh_dflt.o.d  -nostdinc -isystem /usr/lib/gcc/i486-linux-gnu/4.6/include -I/usr/src/linux-headers-3.2.0-4-common/arch/x86/include -Iarch/x86/include/generated -Iinclude  -I/usr/src/linux-headers-3.2.0-4-common/include -include /usr/src/linux-headers-3.2.0-4-common/include/linux/kconfig.h   -I/home/primary/Downloads/intel-536-537/coredrv -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -m32 -msoft-float -mregparm=3 -freg-struct-return -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -Wa,-mtune=generic32 -ffreestanding -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fomit-frame-pointer -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -Wall -O3   -I/lib/modules/`uname -r`/build/include -isystem ../inc -fno-common -DCONFIG_MODULES -DMODULE -DINTEL_MODEM_TYPE=\"536EP\" -DTARGET_SELAH -DDEBUG_LINUX  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(wwh_dflt)"  -D"KBUILD_MODNAME=KBUILD_STR(Intel536)" -c -o /home/primary/Downloads/intel-536-537/coredrv/.tmp_wwh_dflt.o /home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.c

source_/home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.o := /home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.c

deps_/home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.o := \

/home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.o: $(deps_/home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.o)

$(deps_/home/primary/Downloads/intel-536-537/coredrv/wwh_dflt.o):
